version: '3'
services:
  test:
    build: .
    volumes:
      - .:/python
    working_dir: /python
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:13-3.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres